const cvs=document.getElementById('game'),ctx=cvs.getContext('2d');
const overlay=document.getElementById('overlay'),startBtn=document.getElementById('start'),teamsEl=document.getElementById('teams'),ultEl=document.getElementById('ultText');
const joy=document.getElementById('joy'),knob=document.getElementById('knob'),atk=document.getElementById('attack'),ultBtn=document.getElementById('ult');
let W,H,cam={x:0,y:0},state='menu',tick=0,msg='',player,bots=[],walls=[],boxes=[],shots=[],cubes=[],gasR,joyV={x:0,y:0},aim={x:1,y:0},touchId=null;
const MW=3600,MH=2600,rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function size(){W=cvs.width=innerWidth*devicePixelRatio;H=cvs.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);W=innerWidth;H=innerHeight} addEventListener('resize',size);size();
function ent(x,y,me=false){return{x,y,r:24,hp:me?5200:3600,max:me?5200:3600,pow:0,ammo:3,ammoT:0,ult:0,dead:false,cd:0,me,ang:0,hitFlash:0}}
function reset(){state='play';tick=0;msg='';overlay.style.display='none';player=ent(MW/2,MH/2,true);bots=[];shots=[];cubes=[];walls=[];boxes=[];gasR=1900;for(let i=0;i<9;i++){let a=i/9*Math.PI*2,rr=rand(700,1200);bots.push(ent(MW/2+Math.cos(a)*rr,MH/2+Math.sin(a)*rr));}for(let i=0;i<55;i++)walls.push({x:rand(180,MW-350),y:rand(180,MH-300),w:rand(90,230),h:rand(70,190)});for(let i=0;i<38;i++)boxes.push({x:rand(120,MW-120),y:rand(120,MH-120),r:25,hp:1400});}
function hpMax(e){return e.max+e.pow*420}function dmg(e){return 420+e.pow*55}
function blocked(x,y,r){if(x<r||y<r||x>MW-r||y>MH-r)return true;return walls.some(w=>x+r>w.x&&x-r<w.x+w.w&&y+r>w.y&&y-r<w.y+w.h)}
function move(e,dx,dy){let sp=e.me?4.5:3.2;if(dx||dy){let l=Math.hypot(dx,dy);dx=dx/l*sp;dy=dy/l*sp;e.ang=Math.atan2(dy,dx);if(!blocked(e.x+dx,e.y,e.r))e.x+=dx;if(!blocked(e.x,e.y+dy,e.r))e.y+=dy;}}
function shoot(e,ult=false){if(e.dead||e.cd>0)return;if(!ult){if(e.ammo<1)return;e.ammo--;e.ammoT=0;e.cd=24}else{if(e.ult<5)return;e.ult=0;e.cd=36}let base=e.me?Math.atan2(aim.y,aim.x):e.ang;let n=ult?9:5,spread=ult?.95:.58;for(let i=0;i<n;i++){let a=base-spread/2+spread*(i/(n-1));shots.push({x:e.x,y:e.y,vx:Math.cos(a)*(ult?11:9),vy:Math.sin(a)*(ult?11:9),life:ult?42:32,own:e,dam:dmg(e)*(ult?1.15:1)});} }
atk.ontouchstart=e=>{e.preventDefault();shoot(player)};atk.onclick=()=>shoot(player);ultBtn.ontouchstart=e=>{e.preventDefault();shoot(player,true)};ultBtn.onclick=()=>shoot(player,true);startBtn.onclick=reset;
function hit(e,dam,owner){e.hp-=dam;e.hitFlash=8;if(owner===player&&e!==player)player.ult=clamp(player.ult+1,0,5);if(e.hp<=0){e.dead=true;cubes.push({x:e.x,y:e.y,r:14});}}
function ai(b){if(b.dead)return;let targets=[player,...bots].filter(e=>e!==b&&!e.dead),t=targets.sort((a,c)=>dist(b,a)-dist(b,c))[0];if(!t)return;let dx=t.x-b.x,dy=t.y-b.y,d=Math.hypot(dx,dy);b.ang=Math.atan2(dy,dx);if(d>360)move(b,dx,dy);else if(d<170)move(b,-dx,-dy);else move(b,rand(-1,1),rand(-1,1));if(d<520&&Math.random()<.025)shoot(b);}
function update(){if(state!=='play')return;tick++;gasR=Math.max(250,1900-tick*.13);move(player,joyV.x,joyV.y);if(joyV.x||joyV.y)aim={x:joyV.x,y:joyV.y};[player,...bots].forEach(e=>{if(e.dead)return;if(e.cd>0)e.cd--;if(e.ammo<3){e.ammoT++;if(e.ammoT>=60){e.ammo++;e.ammoT=0}}let gd=Math.hypot(e.x-MW/2,e.y-MH/2);if(gd>gasR&&tick%20===0)hit(e,180,null)});bots.forEach(ai);
shots=shots.filter(s=>{s.x+=s.vx;s.y+=s.vy;s.life--;if(blocked(s.x,s.y,4)||s.life<=0)return false;for(const box of boxes){if(box.hp>0&&Math.hypot(s.x-box.x,s.y-box.y)<box.r){box.hp-=s.dam;if(box.hp<=0)cubes.push({x:box.x,y:box.y,r:14});return false}}for(const e of [player,...bots])if(e!==s.own&&!e.dead&&Math.hypot(s.x-e.x,s.y-e.y)<e.r){hit(e,s.dam,s.own);return false}return true});boxes=boxes.filter(b=>b.hp>0);for(const c of cubes){if(!c.got&&Math.hypot(player.x-c.x,player.y-c.y)<42){c.got=true;player.pow++;player.max+=420;player.hp+=420}}bots.forEach(b=>{for(const c of cubes)if(!c.got&&!b.dead&&Math.hypot(b.x-c.x,b.y-c.y)<42){c.got=true;b.pow++;b.max+=420;b.hp+=420}});cubes=cubes.filter(c=>!c.got);let alive=[player,...bots].filter(e=>!e.dead).length;teamsEl.textContent='남은 팀: '+alive;ultEl.textContent='궁극기 '+player.ult+'/5';ultBtn.classList.toggle('ready',player.ult>=5);if(player.dead)end('패배...');else if(alive===1)end('승리!')}
function end(t){state='end';overlay.style.display='flex';overlay.querySelector('h1').innerHTML=t;overlay.querySelector('p').innerHTML='파워큐브 '+player.pow+'개 획득';startBtn.textContent='다시 플레이'}
function sx(x){return x-cam.x}function sy(y){return y-cam.y}
function drawChar(e){if(e.dead)return;let x=sx(e.x),y=sy(e.y);ctx.save();ctx.translate(x,y);ctx.rotate(e.ang);ctx.fillStyle=e.me?'#8d4de8':'#e64c4c';ctx.fillRect(-20,-20,40,40);ctx.fillStyle='#ffd08b';ctx.fillRect(-9,-17,18,14);ctx.fillStyle='#2a1642';ctx.fillRect(8,-7,38,15);ctx.fillStyle=e.me?'#6b28b9':'#9b1d1d';ctx.fillRect(-20,-28,28,14);ctx.restore();ctx.fillStyle='#111';ctx.fillRect(x-34,y-42,68,8);ctx.fillStyle=e.hitFlash?'#fff':'#20df6c';ctx.fillRect(x-34,y-42,68*(e.hp/hpMax(e)),8);if(e.me){for(let i=0;i<3;i++){ctx.fillStyle=i<e.ammo?'#ffd22c':'#333';ctx.fillRect(x-30+i*22,y-30,16,7)}}if(e.pow){ctx.fillStyle='#b04cff';ctx.font='bold 15px Arial';ctx.fillText('◆'+e.pow,x-10,y-50)}if(e.hitFlash)e.hitFlash--}
function draw(){cam.x=clamp(player.x-W/2,0,MW-W);cam.y=clamp(player.y-H/2,0,MH-H);ctx.clearRect(0,0,W,H);for(let x=-cam.x%80-80;x<W;x+=80)for(let y=-cam.y%80-80;y<H;y+=80){ctx.fillStyle=((Math.floor((x+cam.x)/80)+Math.floor((y+cam.y)/80))%2)?'#69bd48':'#73c953';ctx.fillRect(x,y,80,80)}ctx.fillStyle='rgba(150,255,120,.35)';ctx.beginPath();ctx.arc(sx(MW/2),sy(MH/2),gasR,0,Math.PI*2);ctx.rect(W,0,-W,H);ctx.fill('evenodd');ctx.strokeStyle='#52ff5b';ctx.lineWidth=7;ctx.beginPath();ctx.arc(sx(MW/2),sy(MH/2),gasR,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#a85c29';walls.forEach(w=>ctx.fillRect(sx(w.x),sy(w.y),w.w,w.h));boxes.forEach(b=>{ctx.fillStyle='#8b551d';ctx.fillRect(sx(b.x-27),sy(b.y-27),54,54);ctx.fillStyle='#df992e';ctx.fillRect(sx(b.x-20),sy(b.y-20),40,40)});cubes.forEach(c=>{ctx.fillStyle='#a541ff';ctx.fillRect(sx(c.x-13),sy(c.y-13),26,26);ctx.fillStyle='#eee';ctx.fillRect(sx(c.x-5),sy(c.y-5),10,10)});shots.forEach(s=>{ctx.fillStyle='#ffe27a';ctx.beginPath();ctx.arc(sx(s.x),sy(s.y),5,0,7);ctx.fill()});[...bots,player].forEach(drawChar)}
function loop(){update();if(state!=='menu')draw();requestAnimationFrame(loop)}loop();
function joySet(t){let r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=t.clientX-cx,dy=t.clientY-cy,l=Math.hypot(dx,dy),m=45;if(l>m){dx=dx/l*m;dy=dy/l*m}knob.style.left=38+dx+'px';knob.style.top=38+dy+'px';joyV={x:dx/m,y:dy/m}}
joy.addEventListener('touchstart',e=>{touchId=e.changedTouches[0].identifier;joySet(e.changedTouches[0])},{passive:false});joy.addEventListener('touchmove',e=>{for(const t of e.changedTouches)if(t.identifier===touchId)joySet(t)},{passive:false});joy.addEventListener('touchend',e=>{for(const t of e.changedTouches)if(t.identifier===touchId){touchId=null;joyV={x:0,y:0};knob.style.left='38px';knob.style.top='38px'}},{passive:false});
